# Generated by Django 3.2.8 on 2021-11-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.FilePathField(blank=True, default=None, null=True, path='/project_images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.FilePathField(blank=True, default=None, null=True, path='/project_images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.FilePathField(blank=True, default=None, null=True, path='/project_images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.FilePathField(blank=True, default=None, null=True, path='/project_images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.FilePathField(blank=True, default=None, null=True, path='/project_images'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
